title: My Blog
description: My personal blog
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/ 